### ISSUE TITLE
pip install tejaas errors

### ISSUE THREAD

**Issue by wang-xc123** [soedinglab/tejaas#4]
Hi,
    I want to install tejaas in my computer.  my python version is 3.7.8, and my pip version is 20.2.3 (python 3.7).   I already installed mkl and other necessary python packages for tejaas using conda.   I then want to install tejaas using   pip install tejaas  command, but get the follow errors:
ERROR: Could not find a version that satisfies the requirement tejaas (from versions: none)
ERROR: No matching distribution found for tejaas

Could you give me some suggestion to install tejaas. Thanks!

**Comment by francosimonetti** [comment]
Hi @wang-xc123,

The pip installer from tejaas is not available yet. I'm sorry for the confusion in the help page.
In the meantime you can install tejaas by cloning the repository, installing the requirements and compiling the C libraries.

`git clone https://github.com/soedinglab/tejaas.git`
`cd tejaas/lib`
`make clean`
`make`
`cd ..`
`tests/run_mwe.sh`

if you get an error `mkl.h not found`, replace line 3 of `lib/Makefile` that looks like this:
`LIBFLAGS := -L${MKLROOT}/lib/intel64 -Wl,--no-as-needed -lmkl_intel_ilp64 -lmkl_sequential -lmkl_core -lpthread -lm -ldl -std=c99`
for this one:
`LIBFLAGS := -L${MKLROOT}/lib/intel64 -Wl,--no-as-needed -lmkl_rt -lpthread -lm -ldl -std=c99`

It might do the trick. If you need to set MKLROOT, check the MKL installation path and run this in your terminal before running the Makefile, it usually looks something like this:
`export MKLROOT=/opt/intel/oneapi/mkl/2021.3.0`
`source /opt/intel/oneapi/setvars.sh`

Franco

**Comment by wang-xc123** [comment]
Thank you for your help.  I now finish installing it.
