### ISSUE TITLE
GTF read error

### ISSUE THREAD

**Issue by wang-xc123** [soedinglab/tejaas#5]
I have run tejaas in my computer, and get the fellow errors:
```
2021-08-17 18:10:28,054 | utils.args | INFO | Running TEJAAS v1.0.1
2021-08-17 18:10:28,056 | utils.args | INFO | Method: rr
2021-08-17 18:10:28,056 | utils.args | INFO | Null Model: perm
2021-08-17 18:10:28,056 | utils.args | INFO | Sigma_beta: 0.1
2021-08-17 18:10:28,056 | __main__ | DEBUG | Using 1 cores
2021-08-17 18:10:28,068 | iotools.data | DEBUG | Reading expression levels for trans-eQTL discovery
2021-08-17 18:10:28,469 | iotools.data | DEBUG | Reading expression levels for target gene discovery
2021-08-17 18:10:32,681 | iotools.data | DEBUG | Found 16759 genes of 91 samples
2021-08-17 18:10:32,681 | iotools.data | DEBUG | Reading gencode file for gene information
2021-08-17 18:10:32,977 | iotools.data | DEBUG | Selecting common samples of genotype and gene expression
2021-08-17 18:10:32,977 | iotools.data | DEBUG | Before expression selection: 16759 genes from 91 samples
Traceback (most recent call last):
  File "/ipm/wxc/tools/tejaas/tejaas/bin/../main.py", line 71, in <module>
    data.load()
  File "/ipm/wxc/tools/tejaas/tejaas/iotools/data.py", line 248, in load
    expression_selected = rpkm._normalize_expr(expression[:, exprmask][indices, :])
IndexError: arrays used as indices must be of integer (or boolean) type
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[15854,1],0]
  Exit code:    1
--------------------------------------------------------------------------
```

It seems something wrong in my expression data.  My expression data is a tab format file, the expression value were log2 transformed.   How can I solve this problem. Thanks

**Comment by francosimonetti** [comment]
Hi @wang-xc123,

It seems a problem with file formats. Could you post a short sample of your expression format? it should have sample names in the first line and gene names as the first column.
Could you also tell us which gencode version are you using for the gene annotations? This was tested with gencode v26, but it could be that newer versions have a slightly different format and it breaks

**Comment by wang-xc123** [comment]
Hi, francosimonetti, 
my expression data looked like this:

Gene_IDs	Aa-0	Alc-0	Bak-2	Ey15-2	ICE102	ICE107	ICE111	ICE112	ICE119
AT1G01010	4.26	4.42	4.75	5.17	4.38	4.64	4.45	4.8	4.24
AT1G01020	1.92	2.54	1.82	1.45	1.93	2.26	2.1	1.67	1.63
AT1G01030	0.82	1.6	0.64	1.59	0.89	1.5	1.08	-0.09	-0.04
AT1G01046	1.86	1.82	2.28	1.29	2.29	3.18	2.13	2.18	2.24
AT1G01050	5.26	5.27	5.92	5.12	5.82	5.81	5.68	5.21	5.37

And my gtf file is from arabidopsis TAIR10,  the format is:
chr1    TAIR10  exon    3631    3913    .       +       .       gene_id "AT1G01010"; transcript_id "AT1G01010.1"; exon_number "1"
chr1    TAIR10  exon    3996    4276    .       +       .       gene_id "AT1G01010"; transcript_id "AT1G01010.1"; exon_number "2"

the vcf file is imputed by beagle, the format is as follows:
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  Aa-0    Alc-0   Bak-2   Ey15-2
1       266     rs1     G       A       .       PASS    .       GT      0|0     0|0     0|0     0|0
1       346     rs2     C       T       .       PASS    .       GT      0|0     0|0     0|0     1|1

**Comment by francosimonetti** [comment]
@wang-xc123 I think the problem is with the gtf annotations. It probably loads zero genes and that's why it fails.
Tejaas assumes a slightly different gtf format, normally from gencode, and selects only 'protein_coding" and 'lncRNA' genes from the annotation file. The TAIR10 annotation might not match these terms or not even have these annotations for every gene. You can change these terms with the --biotype flag to put the terms appropriate for your gtf file (e.g "protein_coding_gene"), or you could just put "all" to use all genes. I will need to introduce a small change for the later to work. 
Do you have a link to download the gtf file you are using?

The expression and VCF files look correct.

**Comment by wang-xc123** [comment]
I download TAIR10 gff file from  ftp://ftp.arabidopsis.org/home/tair/Genes/TAIR10_genome_release/TAIR10_gff3/TAIR10_GFF3_genes.gff
and transferred to gtf format using gffread. I also write a perl script to convert the gff to gtf myself, but still get the error.
the gtf file convert by myself is:

chr1    TAIR10  gene    3631    5899    .       +       .       gene_id "AT1G01010"; transcript_id "AT1G01010"; gene_type "protein_coding"; gene_name "AT1G01010"; transcript_type "protein_coding"; transcript_name "";
chr1    TAIR10  transcript      3631    5899    .       +       .       gene_id "AT1G01010"; transcript_id "AT1G01010.1"; gene_type "protein_coding"; gene_name "AT1G01010"; transcript_type "protein_coding"; transcript_name "AT1G01010.1";
chr1    TAIR10  exon    3631    3913    .       +       .       gene_id "AT1G01010"; transcript_id "AT1G01010.1"; gene_type "protein_coding"; gene_name "AT1G01010"; transcript_type "protein_coding"; transcript_name "AT1G01010.1";
chr1    TAIR10  CDS     3760    3913    .       +       0       gene_id "AT1G01010"; transcript_id "AT1G01010.1"; gene_type "protein_coding"; gene_name "AT1G01010"; transcript_type "protein_coding"; transcript_name "AT1G01010.1";
chr1    TAIR10  exon    3996    4276    .       +       .       gene_id "AT1G01010"; transcript_id "AT1G01010.1"; gene_type "protein_coding"; gene_name "AT1G01010"; transcript_type "protein_coding"; transcript_name "AT1G01010.1";
 
Thank you for your patience

**Comment by wang-xc123** [comment]
I download TAIR10 gff file from  ftp://ftp.arabidopsis.org/home/tair/Genes/TAIR10_genome_release/TAIR10_gff3/TAIR10_GFF3_genes.gff
and transferred to gtf format using gffread. I also write a perl script to convert the gff to gtf myself, but still get the error.
the gtf file convert by myself is:

chr1    TAIR10  gene    3631    5899    .       +       .       gene_id "AT1G01010"; transcript_id "AT1G01010"; gene_type "protein_coding"; gene_name "AT1G01010"; transcript_type "protein_coding"; transcript_name "AT1G01010";
chr1    TAIR10  transcript      3631    5899    .       +       .       gene_id "AT1G01010"; transcript_id "AT1G01010.1"; gene_type "protein_coding"; gene_name "AT1G01010"; transcript_type "protein_coding"; transcript_name "AT1G01010.1";
chr1    TAIR10  exon    3631    3913    .       +       .       gene_id "AT1G01010"; transcript_id "AT1G01010.1"; gene_type "protein_coding"; gene_name "AT1G01010"; transcript_type "protein_coding"; transcript_name "AT1G01010.1";
chr1    TAIR10  CDS     3760    3913    .       +       0       gene_id "AT1G01010"; transcript_id "AT1G01010.1"; gene_type "protein_coding"; gene_name "AT1G01010"; transcript_type "protein_coding"; transcript_name "AT1G01010.1";
chr1    TAIR10  exon    3996    4276    .       +       .       gene_id "AT1G01010"; transcript_id "AT1G01010.1"; gene_type "protein_coding"; gene_name "AT1G01010"; transcript_type "protein_coding"; transcript_name "AT1G01010.1";
 
Thank you for your patience

**Comment by francosimonetti** [comment]
I've pushed an update version to read GTF files. Try it and let me know if it works. It should give a few warnings or errors if something is off.

If you don't want to filter genes by biotype, just use the flag "--biotype" with no parameter afterwards. This is set to accept all biotypes. Otherwise the default biotypes are "protein_coding lncRNA".

The GTF file obtained from the GFF3 and converted with gffread didn't work for me, it deleted (or changed) all the 'gene' features to transcripts. So maybe that is not the best option.

The formatted GTF file you created with your perl script should work. Just remember that it is a tab separated file and that the last field contains space separated annotations (gene_id "AT1G0001"; etc..)

If something doesn't work, we can try to improve the current solution to be more user friendly. Good luck!

**Comment by wang-xc123** [comment]
Hi, francosimonetti,
    I now can run my data using both the old and updated tejaas. The problem is that some line in my gtf file missed the gene_type infomation.  
    Thank you for your kindly help.
